### PR TITLE
Folder icon detection

### LINKED ISSUE #262: Folder icon detection [$50]
It looks like we don't show the proper icons for several folders. I'm not sure if this just needs to be hooked up from what EDS gives us or we need some kind of heuristic. It looks like the only one that Evolution picks up that we don't currently in "Drafts"

screenshot from 2018-10-17 14 15 30 2x

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/64895548-folder-icon-detection?utm_campaign=plugin&utm_content=tracker%2F59850425&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59850425&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by marbetschar**
Fixes #262.

Implemented similar to [how it is done in Evolution](https://gitlab.gnome.org/GNOME/evolution/-/blob/2fa97de820634ac002784165bb122bc32e651235/src/mail/em-folder-tree-model.c#L692-771).

However, this PR does not cover the following:

- Icon detection for Templates folder (because there is no `Camel.FolderInfoFlags.TYPE_TEMPLATE`)
- Icon detection for local folders (seemed like a legacy thing, so I did not spent any time on this - [if someone needs this, here is how its done in Evolution](https://gitlab.gnome.org/GNOME/evolution/-/blob/2fa97de820634ac002784165bb122bc32e651235/src/mail/em-folder-tree-model.c#L726-738))

### CODE REVIEW

**Comment by marbetschar** [comment]
@davidmhewitt when you have some time would be great to get a review for this, because there are a few similarities to your current PR for message archival support. I'm happy to change anything that makes work easier in https://github.com/elementary/mail/pull/542

**Comment by marbetschar** [comment]
anyone of @elementary/desktop-developers got some time to review this?

**Comment by jeremypw** [comment]
The code looks OK in principle but I am unable to test it in practice as I am unable to get Mail to work with my Gmail account :disappointed:

**Comment by marbetschar** [comment]
@jeremypw thanks for taking time to look at this PR :)

On my end it works without issue when setting up a Gmail account in Evolution - I just need to provide the E-Mail address, and Evolution retrieves all the required information automatically. Although, this is on Odin using Evolution `3.36.4-0ubuntu1` - maybe that's the culprit?

**Comment by jeremypw** [comment]
I was trying to set it up in System Settings/Online Accounts (on Odin).  I'll try Evolution.

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
