### PR TITLE
Added support for Unified Inbox for Office 365 accounts

### PR DESCRIPTION
**Pull request by marbetschar**
Fixes https://github.com/elementary/mail/issues/737

The root cause is, Office 365 connected through EWS uses `Inbox` as folder name instead of the expected `INBOX`. In the code I mitigated this, by checking for the `backend_name`: If it matches `ews` we are adjusting the folder name accordingly.

If you want to test this, make sure to configure two mail accounts - and one of them connected to Office 356 using the  method described here: https://www.marco.betschart.name/areas/elementary-os/missing-features-and-workarounds#oauth-support-modern-authentication

### CODE REVIEW

**Comment by meisenzahl** [comment]
@marbetschar can a general solution be implemented here using [string.ascii_casecmp](https://valadoc.org/glib-2.0/string.ascii_casecmp.html)?

**Comment by marbetschar** [comment]
@meisenzahl indeed. Thanks for the hint!

**Comment by marbetschar** [comment]
@meisenzahl I think _now_ I understand what you meant: Unfortunately this is not possible atm, since the folder name [is passed along `get_folder_info`](https://github.com/elementary/mail/blob/1bd0309f22f1833cc6d3a829de4dd2fc19312216/src/FoldersView/GroupedFolderSourceItem.vala#L98) which in turn fails if the folder name does not match exactly.

So how folder names are compared exactly is up to EDS.

**Review by meisenzahl — APPROVED** [review]
LGTM

**Pull request merged**
