### PR TITLE
Archive message support

### LINKED ISSUE #260: Ability to archive a message
<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64895408-ability-to-archive-a-message?utm_campaign=plugin&utm_content=tracker%2F59850425&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59850425&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #260 

This is largely working but the undo functionality doesn't.

`Camel.Folder.transfer_messages_to` is seemingly supposed to return a list of **new** UIDs for the messages that have been moved. It should then be possible to use those UIDs to move the messages back to the original folder. But for some reason, we're not getting that list of UIDs back from Camel and I haven't had the chance to look into why yet.

### CODE REVIEW

**Comment by marbetschar** [comment]
Wanted to tackle the "Undo" issue in this PR, but I guess I stumbled upon another bug:

When I click the Archive Icon in the Toolbar, the Mail app seems to start an endless loop outputting the below information. However, when I restart the Mail app, the message was moved to Archive folder.

FWIW: I've configured two Mail accounts (Office 365 and Yandex) using [these server settings](https://www.marco.betschart.name/areas/elementary-os/missing-features-and-workarounds#manage-mail-accounts). The behavior below occurs for both accounts.

```bash
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.082: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.082: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.082: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.314: CLIENT[0x559490b3beb0]: yielding operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.315: CLIENT[0x559490b3beb0]: successfully read 3384 bytes from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.316: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.316: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.316: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.377: CLIENT[0x559490b3beb0]: yielding operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.377: CLIENT[0x559490b3beb0]: successfully read 3411 bytes from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.377: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.378: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.378: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.385: CLIENT[0x559490b3beb0]: yielding operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.385: CLIENT[0x559490b3beb0]: successfully read 3398 bytes from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.386: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.386: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.386: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.455: CLIENT[0x559490b3beb0]: yielding operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.455: CLIENT[0x559490b3beb0]: successfully read 3395 bytes from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.456: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.456: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.456: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.525: CLIENT[0x559490b3beb0]: yielding operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.525: CLIENT[0x559490b3beb0]: successfully read 3384 bytes from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.526: CLIENT[0x559490b3beb0]: starting to read data from TLS connection
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.526: CLIENT[0x559490b3beb0]: claiming operation OP_READ
(io.elementary.mail:17458): GLib-Net-DEBUG: 09:52:04.526: CLIENT[0x559490b3beb0]: claiming operation OP_READ succeeded

```

**Comment by davidmhewitt** [comment]
It's entirely possible there's something wrong with my logic somewhere :sweat_smile: 

I've just tried testing this again with the Google Mail account I used last time and it doesn't work at all now. But I understand why. We also need to do some checking to see if there is a valid archive folder for a message before enabling the archive action. It seems my account doesn't have an archive folder anymore (not sure where it's gone?!), so there's nowhere for the code to move messages to, and it just silently fails when you click the archive button.

I'm happy for you to continue work on this branch if you've got the time to investigate though!

**Comment by marbetschar** [comment]
Asked for help in the EDS repository: https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/303

**Comment by marbetschar** [comment]
According to the answers of the EDS Issue I opened it is expected for `transfer_messages_to_sync` to output null for `transferred_uids` in _some_ cases. In my last commit I fixed the VAPI accordingly.

However, this still leaves us with the question of how to undo the archival of the moved messages. @davidmhewitt why can't we just reuse the already known `uids`?

**Comment by marbetschar** [comment]
@davidmhewitt any chance we can get this merged, but without undo for archiving? I really miss the archiving functionality in the new Mail and at the sime time did not find any viable solution for undo :(

**Comment by marbetschar** [comment]
@davidmhewitt I made some further testing and it seems like `transfer_messages_to` is always `null` [when we transfer messages within the same store](https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/303#note_1048151).

Since I was unable to implement Undo for archiving, and Evolution itself is not able to undo archiving too I removed the undo toast completely.

Since most of the code was written by you, is there anything left which should be done before we send the code in for a review?

**Comment by davidmhewitt** [comment]
Feel free to send it for review, I don't have anything more to add

**Review by danrabbit — APPROVED** [review]
Makes sense to create the move handler class and things seem to work as expected :)

**Pull request merged**
