### PR TITLE
Add basic email autocompletion

### PR DESCRIPTION
**Pull request by tintou**

### CODE REVIEW

**Comment by danrabbit** [comment]
I'm getting `(io.elementary.mail:4334): eds-WARNING **: edsf-persona-store.vala:2609: Error in address book view query: Authentication required`

**Comment by danrabbit** [comment]
After making Evolution grab the contacts I can confirm that it works :)

**Comment by danrabbit** [comment]
I think the avatar here is probably too small to be useful.

screenshot from 2017-08-01 13 25 00

**Comment by btkostner** [comment]
I like the idea of having two lines. One for the name, and one for the email.

**Pull request merged**
