### PR TITLE
Composer: set parent internally, use present

### PR DESCRIPTION
**Pull request by danirabbit**
Also fix some places where we assume that `active_window` is a `MainWindow` and not a `Composer`

### CODE REVIEW

**Review by leolost2605 — CHANGES_REQUESTED** [review]
In `Application` the instantiation of the `Composer` has to be changed in the SOUP 3 part too, I think

**Review by leolost2605 — APPROVED** [review]
👍
I only got one (maybe very stupid) question: why do we set `transient_for` on the composer window? What does it actually do in this case?

**Comment by danirabbit** [comment]
@leolost2605 it makes it so the composer window can’t go behind the main window and so that when you move the main window to another workspace, its composer children will move with it.

it might be that this is actually not desirable tbh. I don’t have super strong feelings about it

**Comment by leolost2605** [comment]
Ah ok thank you 😅

I personally think that's quite useful in this case 🤷

**Pull request merged**
