### PR TITLE
Re-adds "Send by Email" contract

### LINKED ISSUE #666: Send via email contractor option
## Problem

When I want to send something via email, I have to open the app and then attach the file to send it.

## Proposal

The old mail app on elementary OS 5 had used contractor to provide a send via email option when right clicking on a file.

## Prior Art

elementary OS 5 mail app

### PR DESCRIPTION
**Pull request by marbetschar**
Fixes #666.

### CODE REVIEW

**Comment by Marukesu** [comment]
I believe we should make files use the [Email Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Email) instead of re-adding the contract in mail. Contracts cannot be provided by sandboxed applications, so they will be useless when mail gets flatpaked.

**Comment by marbetschar** [comment]
Makes sense, thanks for pointing that out! Will look into it.

**Comment by marbetschar** [comment]
Converting to draft, since using the Portal is the better solution. Will close this as soon as the feature itself is re-added anyhow.

**Comment by marbetschar** [comment]
Superseded by https://github.com/elementary/mail/pull/682

**Pull request closed without merging**
