### PR TITLE
Add support for inline images in the composer

### PR DESCRIPTION
**Pull request by leolost2605**
- Add support for inline images in the composer using cid + mimepart. CID + mimepart seems to be the most widely used technique for local inline images (alternatives would e.g. be a base64 encoded image directly inside the html body).
- Also update some margins for gtk4

### CODE REVIEW

**Comment by zeebok** [comment]
Code looks good, I will give this a test tonight!

**Comment by leolost2605** [comment]
Ok so the last commit removes the image when the attachment is removed. I'll probably do the same for the other way round.

Also I thought maybe we shouldn't show the attachment at all?

**Comment by zeebok** [comment]
> Also I thought maybe we shouldn't show the attachment at all?

If that can be done without too much circumvention of code, yeah that might be the cleanest experience. Maybe @danirabbit or @elementary/ux have a strong reason to have the attachment visible?

**Comment by zeebok** [comment]
But the fix you provided to match the inline and the attachment works like a charm!

**Comment by leolost2605** [comment]
No attachment is shown now (i just set `no_show_all` on inline attachments :))
Also only images can now be selected in the filechooser

**Review by zeebok — APPROVED** [review]

**Pull request merged**
