### PR TITLE
MessageListItem: Fix resizing

### PR DESCRIPTION
**Pull request by leolost2605**
Fixes some annoying resizing of the window or the paned position when the window is small and sender/recipient addresses or the subject include a long word by using the wrap mode `WORD_CHAR`.

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
This fixes the issue for some messages, but not if they have an attachment with a long title (which does not wrap). In that case the window still resizes.

**Comment by jeremypw** [comment]
This now fixes the attachment issue. The only thing I don't like is that the minimum width of the address fields is only about 4 chars so you can get very tall thin fields.  Not sure what the best solution is to this.   Maybe the date field should also be responsive and/or a minimum width/height applied to the address fields?

**Comment by leolost2605** [comment]
Now a min width of 10 (debatable i'm open to suggestions) characters is applied and the datetime label is ellipsized in the middle (also debatable). I've got no special preference here so tell me what you think :)

(And cc is now also wrapped with word_char, i forgot that previously)

**Comment by jeremypw** [comment]
I find wrapping the date with `wrap_mode = WORD` looks better (in English locale at least) and all the info remains visible - what do you think? With the date shrinking the min width of the address is less important as the overall minimum width is limited by the header bar anyway, but 10 is OK.

**Comment by leolost2605** [comment]
@jeremypw done :)

**Pull request closed without merging**
