### PR TITLE
Grouped Folders Added: Archive

### PR DESCRIPTION
**Pull request by marbetschar**
This PR builds upon the previous Grouped Folder PR's and adds support for the well known folders Archive, Draft and Sent:

116965768-df906000-acae-11eb-8e6e-39e9d61a6daa

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
I can confirm that the "Archive" folder seems to be working as expected. However, I don't have anything in "Sent" or "Drafts" and I'm getting the following Terminal output:

```
** (io.elementary.mail:69682): CRITICAL **: 11:01:09.060: mail_grouped_folder_source_item_strip_folder_full_name: assertion 'folder_uri != NULL' failed

** (io.elementary.mail:69682): CRITICAL **: 11:01:09.064: mail_grouped_folder_source_item_strip_folder_full_name: assertion 'folder_uri != NULL' failed

(io.elementary.mail:69682): camel-WARNING **: 11:01:11.640: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError

(io.elementary.mail:69682): camel-WARNING **: 11:01:12.416: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError

(io.elementary.mail:69682): camel-WARNING **: 11:01:12.774: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError
```

I would recommend splitting this up into separate branches so we can verify and debug each folder separately

**Comment by marbetschar** [comment]
@danrabbit dropped all non-archive folder related stuff.

**Review by danrabbit — COMMENTED** [review]
Way less terminal output! I'm still getting a single `(io.elementary.mail:78575): camel-WARNING **: 12:06:35.193: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError` but I can't see anything obviously wrong or broken

**Comment by marbetschar** [comment]
I guess the warning is thrown here - but I have no clue why:

https://github.com/elementary/mail/blob/9f5f261f7280f58e0ea1b6d817dbc06a9e7025bf/src/FoldersView/GroupedFolderSourceItem.vala#L93

**Review by danrabbit — APPROVED** [review]
It's working, so I guess let's come back to the error :shrug:

**Pull request merged**
