### PR TITLE
Fix MailBackendSimpleSasl has an empty CamelServiceAuthType

### PR DESCRIPTION
**Pull request by marbetschar**
This PR attempts to fix the critical message printed at the startup of Mail:

```
(io.elementary.mail:6659): camel-CRITICAL **: 11:20:27.758: MailBackendSimpleSasl has an empty CamelServiceAuthType
```

Which is caused by the following line in EDS: https://gitlab.gnome.org/GNOME/evolution-data-server/-/blob/master/src/camel/camel-sasl.c#L103

However, I'm stuck: Because I can't subclass `Camel.ServiceAuthType`, I simply cast the newly added `SimpleServiceAuthType` to `Camel.ServiceAuthType` which works just fine. However, EDS is still throwing the critical message. @tintou what I'm missing here?

### CODE REVIEW

**Comment by tintou** [comment]
@marbetschar I've fixed the introspection, I haven't actually properly tested it though

**Comment by tintou** [comment]
@marbetschar I've fixed the introspection, I haven't actually properly tested it though

**Comment by tintou** [comment]
@marbetschar I've fixed the introspection, I haven't actually properly tested it though

**Comment by tintou** [comment]
@marbetschar I've fixed the introspection, I haven't actually properly tested it though

**Comment by marbetschar** [comment]
@tintou wow, that's impressive! Thank you so much!! That change would have taken me ages to figure out :laughing:

Things are working flawlessly on my end - not quite sure what you mean with "properly" tested though. I guess we should hand this in for review and see what others think.

**Comment by marbetschar** [comment]
⚠ WARNING: Some changes introduced here caused a SegmentationFault in https://github.com/elementary/mail/pull/679#issuecomment-913172123

No clue why exactly 🤷‍♂️

**Comment by tintou** [comment]
> warning WARNING: Some changes introduced here caused a SegmentationFault in [#679 (comment)](https://github.com/elementary/mail/pull/679#issuecomment-913172123)
> 
> No clue why exactly man_shrugging

We need a backtrace with the symbols enabled to understand why it's the case

**Comment by marbetschar** [comment]
@tintou which simbols are you missing from [the stacktrace linked](https://github.com/elementary/mail/pull/679#issuecomment-913172123)?

**Pull request closed without merging**
