### PR TITLE
Animate message list

### PR DESCRIPTION
**Pull request by tintou**

### CODE REVIEW

**Comment by danrabbit** [comment]
Need that `collapsed` class :p

**Comment by tintou** [comment]
Added

**Comment by tintou** [comment]
Yeah this is not the scope of this merge request, I'm just adding the mechanism here

**Comment by danrabbit** [comment]
When you collapse a message the header it disappears. I also can't confirm the collapsed class is being applied

screenshot from 2017-07-17 13 51 56

**Pull request merged**
