### PR TITLE
MessageListBox: Hide other children while InlineComposer is shown

### PR DESCRIPTION
**Pull request by marbetschar**
This PR is related to https://github.com/elementary/mail/issues/671 where I accidentally changed the sender address while scrolling.

We fix the weird scrolling behavior here by hiding other messages while the InlineComposer is shown.

**Before**

https://user-images.githubusercontent.com/392542/131533890-aa445f52-f175-4a26-96a6-44fb629bf919.mp4

**After**

https://user-images.githubusercontent.com/392542/131533915-62b68fd1-d44d-43ed-9751-0c889bfb8312.mp4

### CODE REVIEW

**Review by tomaswarynyca — APPROVED** [review]

**Comment by tintou** [comment]
I think that in term of UX I'd prefer to keep the other children as I often need to look again at the conversation, a button to detach the composer into a window would be better I think

**Comment by marbetschar** [comment]
@tintou aren't you seeing the whole conversation within the composer itself? At least on my end it cites the whole conversation - so I can simply scroll down to see older messages within the composer.

UX wise I'm not 100% happy with the way things are implemented right now, because I'm regularly struggling with scrolling into the correct direction as described here: https://github.com/elementary/mail/discussions/609

**Comment by danrabbit** [comment]
Maybe @cassidyjames has thoughts, but personally I don't think it would be a terribly experience if we got rid of the inline composer since it adds quite some complexity

**Comment by cassidyjames** [comment]
Yeah I'm not terribly torn either way. Popping into a new window would let us keep the conversation in the main window, which could be handy for reference if the composer is not modal. But I'm also not really a "heavy" email user. :)

**Comment by marbetschar** [comment]
Personally I like the inline composer - IMHO its way less distracting than popping out a new window. But I agree, the proposed solution here is more like fixing a symptom of a more fundamental problem (details here https://github.com/elementary/mail/discussions/609).

So its probably better to inverse the sort of the whole listbox and add the inline composer at the top - instead of adding the compoesr at the bottom and hide messages while its visible?

**Comment by danrabbit** [comment]
I think when we looked at other mail clients, the list of messages was almost always with the newest messages on the bottom and reversing the direction would break the collapsing behavior we currently have

I also don't think hiding messages while composing is a good idea because, as Cass said, it's easier to reference. Even though messages are quoted, it's still a bit harder to follow than just glancing up to the previous message

**Comment by danrabbit** [comment]
Running a super-duper scientific twitter poll to see if we can get some information about how other people feel: https://twitter.com/DanielFore/status/1441090872007806980

**Comment by danirabbit** [comment]
Closing since we decided to remove the inline composer

**Pull request closed without merging**
