### PR TITLE
Fix some attachments not showing up

### LINKED ISSUE #957: Can't download attachment from email
### What Happened?

I have one email with an attachment that I can't download. It's a PDF in a fairly simple email.

image

### Steps to Reproduce

1. Open email
2. There's no download button/file icon

### Expected Behavior

A file icon should appear to be able to download the file.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

```
         eeeeeeeeeeeeeeeee            wout@Framey 
      eeeeeeeeeeeeeeeeeeeeeee         ----------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 7 Horus x86_64 
  eeee   eeeee       eee     eeee     Host: Laptop (12th Gen Intel Core) A8 
 eeee   eeee          eee     eeee    Kernel: 6.2.0-32-generic 
eee    eee            eee       eee   Uptime: 3 hours, 27 mins 
eee   eee            eee        eee   Packages: 1956 (dpkg), 69 (flatpak) 
ee    eee           eeee       eeee   Shell: bash 5.1.16 
ee    eee         eeeee      eeeeee   Resolution: 3000x2000, 3840x2160 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: io.elementary.stylesheet.mint [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: 12th Gen Intel i7-1280P (20) @ 4.700GHz 
      eeeeeee         eeeeeee         GPU: Intel Alder Lake-P 
         eeeeeeeeeeeeeeeee            Memory: 9149MiB / 64003MiB 
```

### PR DESCRIPTION
**Pull request by leolost2605**
Fix some attachments not showing up.

Tries to fix #957  

Only for reference if this doesn't work: the evolution way of getting whether a part is an attachment is (I think) found [here](https://github.com/GNOME/evolution/blob/70d6fcc6c1dcb73a0f8f121df4db9cd782c91a9e/src/em-format/e-mail-part-utils.c#L265)

### CODE REVIEW

**Comment by leolost2605** [comment]
@wout could you maybe test whether this fixes your issue? 
Unfortunately I currently don't have any attachments that don't load

**Comment by wout** [comment]
I'll try to test this asap, I'm swamped at the moment. I've sent you the email in question, maybe it heps to test the issue?

**Comment by leolost2605** [comment]
> I'll try to test this asap, I'm swamped at the moment

No worries, test when you've got enough time :)



> I've sent you the email in question, maybe it helps to test the issue?

Unfortunately the attachment didn't come along probably for the same reason it doesn't show up for you :(

**Comment by wout** [comment]
Okay, I've forwarded you the mail from Mailspring. In Mail, the attachment icon is present at the top left of the email, but the attachment is not visible at the bottom of the mail.

**Comment by leolost2605** [comment]
Unfortunately the attachment showed up in master and this branch for me, maybe Mailspring changed the format or something... 🤷

**Comment by leolost2605** [comment]
Maybe we can just merge this because I don't think it will introduce any regression but it might fix the problem 🤷

**Review by danirabbit — APPROVED** [review]
I can confirm attachments still show up here so :shipit:

**Pull request merged**
